const fishesImages = {
	pike: require('./pike.jpg'),
	carp: require('./carp.jpg'),
	zander: require('./zander.jpg'),
	bream: require('./bream.jpg'),
	perch: require('./perch.jpg'),
	crucian: require('./crucian.jpg'),
	catfish: require('./catfish.jpg'),
	amur: require('./amur.jpg'),
	asp: require('./asp.jpg'),
	roach: require('./roach.jpg'),
	chub: require('./chub.jpg'),
	'white-bream': require('./white-bream.jpg'),
	cod: require('./cod.jpg'),
	tench: require('./tench.jpg'),
	grayling: require('./grayling.jpg'),
	'silver-carp': require('./silver-carp.jpg'),
	trout: require('./trout.jpg'),
	salmon: require('./salmon.jpg'),
	barbel: require('./barbel.jpg'),
	ide: require('./ide.jpg'),
	bleak: require('./bleak.jpg'),
	rudd: require('./rudd.jpg'),
	burbot: require('./burbot.jpg'),
	certa: require('./certa.jpg'),
	dace: require('./dace.jpg'),
	eel: require('./eel.jpg'),
	pigfish: require('./pigfish.jpg'),
	whitefish: require('./whitefish.jpg'),
	garfish: require('./garfish.jpg'),
	danube: require('./danube.jpg')
};

export default fishesImages;